var form = document.createElement('form');
document.body.appendChild(form);
form.method = 'post';
form.action = 'https://l-tike.com/st1/4cycmqgfqmim718b01t6';
var input = document.createElement('input');
input.type = 'hidden';
input.name = 'CERK';
input.value = 'a5bb8b56c0ef60ba67883dc103a8a226';
form.appendChild(input);
form.submit();
